/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Sidebar principal con estructura optimizada
  tutorialSidebar: [
    // Páginas principales
    {
      type: 'doc',
      id: 'programa',
      label: '🏠 Bienvenidos al Reto DevOps',
    },
    {
      type: 'doc',
      id: 'calendario',
      label: '📅 Calendario de Encuentros',
    },
    {
      type: 'doc',
      id: 'plan-de-estudio',
      label: '📋 Plan de Estudio',
    },
    {
      type: 'doc',
      id: 'proyect-fuego',
      label: '🔥 Proyecto Fuego by Roxs',
    },
    {
      type: 'doc',
      id: 'devops',
      label: '🚀 Sobre DevOps',
    },
    {
      type: 'doc',
      id: 'roadmap',
      label: '🗺️ Roadmap DevOps',
    },
    
    // Comunidad
    {
      type: 'category',
      label: '🎥 Comunidad',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'live-youtube',
          label: '📺 DevOps Live YouTube',
        },
      ],
    },
    
    // Programa de Estudio
    {
      type: 'category',
      label: '📚 Programa de Estudio',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: '1️⃣ Semana 1',
          collapsed: true,
          items: [
            'semana-01/dia1',
            'semana-01/dia2',
            'semana-01/dia3',
            'semana-01/dia4',
            'semana-01/dia5',
            'semana-01/dia6',
            'semana-01/dia7',
          ],
        },
        {
          type: 'category',
          label: '2️⃣ Semana 2',
          collapsed: true,
          items: [
            'semana-02/dia8',
            'semana-02/dia9',
            'semana-02/dia10',
            'semana-02/dia11',
            'semana-02/dia12',
            'semana-02/dia13',
            'semana-02/dia14',
          ],
        },
        {
          type: 'category',
          label: '3️⃣ Semana 3',
          collapsed: true,
          items: [
            'semana-03/dia15',
            'semana-03/dia16',
            'semana-03/dia17',
            'semana-03/dia18',
            'semana-03/dia19',
            'semana-03/dia20',
            'semana-03/dia21',
          ],
        },
      ],
    },
    
    // Recursos
    {
      type: 'category',
      label: '🛠️ Recursos',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: '📍 DevOps Projects',
          collapsed: true,
          items: [
            'DevOps-Projects/project0',
            'DevOps-Projects/project1',
          ],
        },
        {
          type: 'category',
          label: '⚙️ DevOps Tools',
          collapsed: true,
          items: [
            'DevOps-Tools/tools',
            'DevOps-Tools/vsc',
            'DevOps-Tools/playgrounds',
            {
              type: 'category',
              label: '🐧 Linux CLI',
              collapsed: true,
              items: [
                {type: 'autogenerated', dirName: 'DevOps-Tools/linux-cli'},
              ],
            },
            {
              type: 'category',
              label: '📝 Uso de Bash',
              collapsed: true,
              items: [
                {type: 'autogenerated', dirName: 'DevOps-Tools/uso-bash'},
              ],
            },
            {
              type: 'category',
              label: '💡 Ejemplos Linux',
              collapsed: true,
              items: [
                {type: 'autogenerated', dirName: 'DevOps-Tools/ejemplos-linux'},
              ],
            },
          ],
        },
        {
          type: 'category',
          label: '📚 Libros DevOps',
          collapsed: true,
          items: [
            'Libros/libros-devops-1',
            'Libros/libros-devops-2',
          ],
        },
      ],
    },
  ],
};

export default sidebars;
